// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/mdblp/seagull/client"

	mock "github.com/stretchr/testify/mock"
)

// SeagullClientAPI is an autogenerated mock type for the SeagullClientAPI type
type SeagullClientAPI struct {
	mock.Mock
}

// GetInfos provides a mock function with given fields: ctx, userID, token
func (_m *SeagullClientAPI) GetInfos(ctx context.Context, userID string, token string) (*client.SeagullDocument, error) {
	ret := _m.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for GetInfos")
	}

	var r0 *client.SeagullDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.SeagullDocument, error)); ok {
		return rf(ctx, userID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.SeagullDocument); ok {
		r0 = rf(ctx, userID, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.SeagullDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPreferences provides a mock function with given fields: ctx, userID, token
func (_m *SeagullClientAPI) GetPreferences(ctx context.Context, userID string, token string) (*client.SeagullDocument, error) {
	ret := _m.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferences")
	}

	var r0 *client.SeagullDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.SeagullDocument, error)); ok {
		return rf(ctx, userID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.SeagullDocument); ok {
		r0 = rf(ctx, userID, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.SeagullDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfile provides a mock function with given fields: ctx, userID, token
func (_m *SeagullClientAPI) GetProfile(ctx context.Context, userID string, token string) (*client.SeagullDocument, error) {
	ret := _m.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *client.SeagullDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.SeagullDocument, error)); ok {
		return rf(ctx, userID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.SeagullDocument); ok {
		r0 = rf(ctx, userID, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.SeagullDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetInfos provides a mock function with given fields: ctx, userID, doc, token
func (_m *SeagullClientAPI) SetInfos(ctx context.Context, userID string, doc *client.SeagullDocument, token string) []error {
	ret := _m.Called(ctx, userID, doc, token)

	if len(ret) == 0 {
		panic("no return value specified for SetInfos")
	}

	var r0 []error
	if rf, ok := ret.Get(0).(func(context.Context, string, *client.SeagullDocument, string) []error); ok {
		r0 = rf(ctx, userID, doc, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// NewSeagullClientAPI creates a new instance of SeagullClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeagullClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SeagullClientAPI {
	mock := &SeagullClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
